Financial-Times/next-metrics

lib/graphite/client.js

I've hammered a second graphite server, so we copy everything to two backends.
We'll then see if the FT graphite is working properly, and catching the correct metrics.

Push metrics to graphite.ft.com as well as hosted graphite

---

lib/graphite/client.js

Hosted graphite apparently has taken away the timestamp requirement for updates. Fortunately it still understands the original format, so its a fairly simple task.

Turns out you need a timestamp to make graphite work

---

Makefile
lib/graphite/client.js
lib/metrics.js
lib/metrics/system/process.js
package.json
tests/graphite/clientSpec.js

We've a zillion metrics in hostgraphite without any values, this stops them being sent. Also added a simple test. Need to add more at some point.
/cc @matthew-andrews @wheresrhys

Filter null values from being sent to graphite

---

lib/metrics/system/process.js

Makes it easier to look for combined minor & patch versions in graphite queries - Eg, find all servers running less than node 0.12.7 - Eg, `0.12.[0123456]`

Collect full node version number

---

lib/metrics.js

As discussed in the dev huddle. We've been experimenting using [`pm2`](http://pm2.keymetrics.io/) to cluster applications within single Heroku instances. This worked successfully but reduced the application metrics by a factor of n for each additional sub process. 
This should fix the above issue by adding the pm2 process id to the graphite key for each application if it exists.
I  will report back with my findings if it works :)

Add pm2 instance id to graphite key if exists

---

lib/metrics/services.js

I've been moving preflight to `node-fetch` (from `request`) and the metrics libraries is missing some instrumentation

Add services from preflight

---

lib/metrics/fetch.js

Should yield, 
```
1.localhost.mattc._.flush.rate 3 1456166764.557
1.localhost.mattc._.fetch.capi-v2-article.count 29 1456166764.557
1.localhost.mattc._.fetch.capi-v2-article.response.status_timeout.count 29 1456166764.557
```

Ensure timeouts appear in the reported stats

---

lib/graphite/client.js

Our Heroku logs are being flooded with these messages and they aren't useful in the slightest. This is causing us to miss vital debugging/diagnostic logs in production environments. Therefore I'm killing them.

Remove metrics client socket close message

---

lib/metrics/services.js

Added the test APIs used in production for the sign up form to stop sentry errors. Must be replaced by production APIs. https://app.getsentry.com/nextftcom/ft-next-signup/issues/115589819/
cc @ifyio @commuterjoy

APIs for the sign up form

---

lib/metrics/services.js

Also included prod and test apis for demographic fields
cc @ifyio, added the prod apis and regex to cover what we use. Please let me know if you spot any I've missed

Add prod apis for signup

---

lib/metrics/services.js
package.json

This should stop the errors in sentry for requests like
https://giftarticle.ft.com/giftarticle/actions/gift
https://giftarticle.ft.com/giftarticle/user/credits
I believe that `next-rtcl-email-api` is the correct application based on its [README](https://github.com/financial-times/next-rtcl-email-api#get-user-credits])
@matthew-andrews @bjfletcher @i-like-robots

Adds gift article to the metrics services

---

README.md
index.js
lib/metrics.js

* expose the `Metrics` constructor (rather than just an instance)
* add ability to turn off auto-flushing (with `flushEvery: false`)
* only instantiate `Proxies` if using the default aggregators

More flexiblity for a non-app context

---

lib/metrics.js

So it's not just dependent on `NODE_ENV`

Allow forcing of Graphite logging

---

lib/metrics/fetch.js
test.js

It's really annoying how fetch metrics aren't isolated enough due to being on the same microtask queuq. This... well I doubt it'll improve matters, but it does at least prioritise handling the response over reporting the metrics. Can't do any harm @richard-still-ft @TheoLeanse @matthew-andrews

applying fetch metrics lazily

---

lib/metrics/services.js

There's been a lot of errors for the following kind of fetch:
`https://api.ft.com/lists?curatedOpinionAnalysisFor=f814d8f7-d38e-31b8-a51f-3882805288fd`
which doesn't show up in graphite because the regex doesn't cover the equality sign (`=`) there
I've simplified the regex, to make sure it catches all fetch errors for `/lists`

fix lists regex

---

lib/metrics/fetch.js

cc @ironsidevsquincy 
Because `this.counters['fetch_' + service + '_status_2xx']` and `this.counters['fetch_' + service + '_status_3xx']` did not exist, [this line](https://github.com/Financial-Times/next-metrics/blob/master/lib/metrics/fetch.js#L64) was throwing an error (`.inc()` cannot be called on undefined) and so every successful 2xx or 3xx response would _also_ increment the number of `that.counters[prefix + '_status_timeout']` or `that.counters[prefix + '_status_failed']`.
As an example, the fetches from `next-api` to `aws-elastic-v3-search` had identical graphs for both `status_2xx` and `status_failed` counts.

Add: 2xx + 3xx fetch counters

---

lib/metrics/services.js

Because of this
https://github.com/Financial-Times/next-flags-ui/blob/d0b712d1ec51e1b6051fbd3dc4e6441f16d2ca6d/server/controllers/flags.js#L26
and just because why not?

Updates flags regex to allow for protocol-less urls

---

README.md
lib/metrics.js
test/unit/lib/metrics.spec.js
test/unit/mock/graphite.mock.js

This mostly means that apps no longer need to specify an
FT_GRAPHITE_APIKEY environment variable just to turn it off. We do this
in Origami Services currently.
Also it feels wrong that every instance of Metrics has to share the same
API keys.

Allow setting API keys through the options object

---

lib/metrics/services.js

cc: @i-like-robots 
The search matcher was also matching the item matcher that was ahead of it in the list so wasn't differentiating.
So have swapped around and also added a matcher for mget differentiated from single item.

Amend: Reorder ES metric matchers

---

lib/graphite/client.js

I'm proposing to get rid of these warnings:
I'd argue that we don't need hundreds of these warning cluttering the output of all next apps. I find that they make development and debugging a bit more tedious than necessary.
Does anybody agree with me?

Do not warn about logging to Graphite being disabled in non-production environment

---

lib/metrics/system/process.js
test/unit/lib/metrics/system/process.spec.js

The full version is something like `v8.11.0`, which doesn't make sense as a metric count.

Don't send full node version to metrics

---

lib/metrics/services.js

Apparently next-es-interface makes calls to www.ft.com/content/:uuid...

Add www-article

---

README.md
lib/graphite/client.js
lib/metrics.js
lib/metrics/fetch.js
test/unit/lib/metrics.spec.js

- Temporarily reinstate HOSTEDGRAPHITE_APIKEY env variable support
- Change behaviour of next-metrics so bad config won't crash an app (see commit message for more detail)

Unblock v2.x.x releases

---

Makefile
README.md
lib/graphite/client.js
lib/metrics.js
lib/metrics/system/process.js
package.json
secret-squirrel.js
test/unit/client.spec.old.js
test/unit/http.spec.old.js
test/unit/lib/metrics.spec.js

FT Graphite (`graphite.ft.com`) no longer exists, so we're removing support for it and optimising this library for FT GraphiteV2.
The `Metrics#init` options `app` and `platform` have been deprecated. Warning messages will be logged if either of these options are specified when calling the `init` method.
Resolves #315.

Remove legacy FT Graphite support

---

lib/metrics.js
test/unit/lib/metrics.spec.js

As we are no longer using this environment variable we want to encourage people to remove it if it still exists in their environment.
🐿 v2.11.0

Log a warning message if `HOSTEDGRAPHITE_APIKEY` env var exists

---

.circleci/config.yml
lib/metrics.js

- A variable had been updated from being a string with a potential value of `'heroku'` to being a `Boolean`, however the usage of the variable had been missed. This PR corrects and inlines the boolean comparison for simplification.
This was preventing the correct metrics being posted

Fix platformIsHeroku comparing boolean to string 'heroku' bug

---

lib/metrics/services.js

Following chat with Sam P, we believe adding qualtrics to the services file will fix the sev 3 error described in this card - https://trello.com/c/yDAnxyZ2.

Add qualtrics to services

---

lib/metrics.js

Well, this is embarrassing @matthew-andrews @commuterjoy 
Meant any histograms (other than fetch and express request ones) accumulated over the lifetime of the process. Memory leak + so, so wrong
How did next survive so long with this bug 🤣 
🐿 v2.12.0

clear custom histo after flushing

---

lib/metrics.js
test/unit/lib/metrics.spec.js

There were some issues when multiple init calls were made. After some investigation I saw that multiple aggregators were added with each init call, which led to custom counter overrides. It seems that was caused by `if(this.graphite)` being `undefined`. this.graphite was used before `this.graphites = [];` was introduced. 
This PR should fix the issue

Fixed init method behaviour when multiple init calls are made

---

.circleci/config.yml
CODEOWNERS
ft.yml
package.json
test/unit/http.spec.old.js

This PR replaces our custom `ft.yml` file with GitHub's standard CODEOWNERS file. The CODEOWNERS file defines the individual or team that is responsible for the code in the repository. Unlike `ft.yml`, code owners will automatically be asked to review any pull requests.
For more information on CODEOWNERS, see https://help.github.com/en/articles/about-code-owners.
Where a repository contains an empty `ft.yml`, no CODEOWNERS file will be created. We did this so we can easily identify which repositories are unowned by looking for the absence of a CODEOWNERS file.
The n-gage package insists that repositories have an ft.yml file. Version 3.4.0 of n-gage removes this requirement. This transformation requires n-gage version 3.4.0 in package.json because it deletes the (otherwise required) ft.yml …

Replace ft.yml with CODEOWNERS file

---

lib/metrics/services.js

A next-preview healthcheck is failing
```js
{
"name": "Metrics: All services for preview registered in next-metrics",
"ok": false,
"checkOutput": "http://test.api.ft.com/internalcontent/42215589-eee1-399f-97ee-c71f61462eb4, http://test.api.ft.com/internalcontent/a65384bb-5017-3184-9e1d-742fb1000ba1, http://test.api.ft.com/internalcontent/31ba72c7-19ec-3bdf-8a1d-a36ec48796e6, http://test.api.ft.com/internalcontent/30649a3b-3139-3c27-a806-6b65df216b80, http://test.api.ft.com/internalcontent/ed8dff25-0110-384f-82fd-d03780d6ec9, http://test.api.ft.com/internalcontent/b03f7d6f-decd-3fbc-9c7b-870794610825 services called but no metrics set up.",
"lastUpdated": "2019-09-04T13:53:39.630Z",
"panicGuide": "See next-metrics/lib/metrics/services.js and set metrics for the service, then release …
```

Add next-preview test api url in services.js

---

.circleci/config.yml
package.json
test/unit/client.spec.old.js

- **Update circleci/node version 6 to 8**
because I got the error below when I try to release new version of next-metrics
```
npx snyk monitor --org=customer-products --project-name=Financial-Times/next-metrics
/bin/bash: npx: command not found
```
https://circleci.com/gh/Financial-Times/next-metrics/2238
`npx` is provided from `npm version ^5.2.0`
The Circle build's npm version is `3.10.10`
----
- **Update `mitm` version to the latest(1.7.0)**
The `npx` issue is resolved  by node version update but I get a different error related to the update.
```
1 failing
1) Logging to graphite
Send metrics to Graphite:
TypeError: normalizeConnectArgs is not a function
at Mitm.connect (node_modules/mitm/index.js:70:14)
at Graphite.log (lib/graphite/client.js:6:247)
at Context.<anonymous> …
```

Update circleci/node version

---

lib/metrics/services.js

Remove `feed` from the service URL as there is now a `country-feed` so this should future proof this a little more.

Update personlised-feed service URL

---

lib/metrics/services.js

trying to clear heimdall alerts
Metrics: All services for eventpromo-api registered in next-metrics
heimdall
https://heimdall.in.ft.com/system?code=next-eventpromo-api#monitored-checks-list
ops-cops card:
https://trello.com/c/PZC87usn/1163-eventpromo-api-alerting

add urls used by eventpromo sync service

---

lib/metrics/services.js

Previously, we had an `www.ft.com` service which acted as a catch-all service but it hid key information. `www.ft.com` was recently removed from the list (see commit https://github.com/Financial-Times/next-metrics/commit/2a0b3e303e6b96fa6bd7b99960badc6f13df8533) in favour of adding more specific APIs and services (e.g. `www.ft.com/content/*`).
Since then we've come across an error about `https://www.ft.com/__origami/service/image/v2/ ` not being registered in `next-metrics`. This PR adds it to the list of services. 
I've also added Origami Build Service v1 to the list, as Sam suggested, so we can find out where we need to update things
Resolves Ops Cop issue: https://trello.com/c/Y2VRF2wp/1220-metrics-all-services-for-es-interface-registered-in-next-metrics-alert

Set up metrics for Origami Build Service

---

lib/metrics/services.js

Previously, we had an `www.ft.com` service which acted as a catch-all service but it hid key information. `www.ft.com` was recently removed from the list (see commit https://github.com/Financial-Times/next-metrics/commit/2a0b3e303e6b96fa6bd7b99960badc6f13df8533) in favour of adding more specific APIs and services (e.g. `www.ft.com/content/*`).
Since then we've come across an error about `https://www.ft.com/syndication` not being registered in next-metrics. This PR adds it to the list of services.
Once this PR is merged, I will have to create a new release in both `n-express` and `n-ui` in order for the change to get picked up.
Resolves Ops Cop issue: https://trello.com/c/ngq2Wqwi/1259-next-syn-list-is-flappy

Set up metrics for next-syn-list

---

lib/metrics/services.js

As the article-email API has now been removed from `next-article` and `service-registry`, we shouldn't have any need for the metric to hang around either.

chore: remove decommed article-email metric

---

lib/metrics/services.js

This is no longer used and as part of decommissioning `next-signup` we're removing this.
[Trello ticket](https://trello.com/c/CkV91VXy/1696-decommission-next-signup-and-next-signup-api)

Remove mship-mock-api

---

lib/metrics/services.js

`next-comments-api` calls the membership graphql service without a
backslash and as a result, it's healthcheck was failing. This PR removes
the need for a backslash so regardless of whether you use one or not,
`next-metrics` will pick it up.

Remove the need for a backslash at end of url

---

lib/metrics/services.js

next article has a failing health check:
`"checkOutput": "https://api-ssl.bitly.com/v4/shorten services called but no metrics set up."`
this PR will hopefully fix that
see https://github.com/Financial-Times/next-article/pull/3679

add Bitly v4 to the services list

---

lib/metrics/services.js

Salesforce APIs are used in `next-subscribe` to retrieve the associated contract of a B2B licence.

Add Salesforce APIs to list of instrumented services

---

lib/metrics/fetch.js

If fetch throws an exception, because for example there is a timeout
exception thrown, then this promise chain wouldn't have had a catch on
it so would have triggered a `unhandledRejection` event. This was
causing enterprise tools to crash when there was a network timeout.
We don't need to actually do anything with this catch though as the
promise chain is only being used for metric collection. The exception
will still bubble through the other promise chains where a consuming
application can handle it properly.

Add catch to promise chain

---

lib/metrics/services.js

🐿 v2.12.4
Work involved in decommissioning next-b2b-prospect

Removes reference to next-b2b-prospect

---

lib/metrics/services.js

Calls to 'https://financiatimescx.eu.qualtrics.com/API/v3/responses/undefined' are not registered so the healthcheck for next-feedback-api is constantly red. 
The Accounts team have added looking into the reason why we make a call to an endpoint with 'undefined' in the url to their backlog, but in the meantime we should allow this call to ensure we don't miss other next-feedback-api healthchecks going red.
https://financialtimes.atlassian.net/jira/software/projects/NOPSCOPS/boards/952?selectedIssue=NOPSCOPS-130

Update qualtrics regex

---

lib/metrics/services.js

This is currently used by next-article.

Adds IG coronavirus map endpoint

---

lib/metrics/services.js

As per `panicGuide` for one of the health checks currently failing in: https://url-management.ft.com/__health.
```
{
"name": "Metrics: All services for url-mgmt-service registered in next-metrics",
"ok": false,
"checkOutput": "https://url-management-api.in.ft.com/api services called but no metrics set up.",
"lastUpdated": "2020-04-21T10:04:12.425Z",
"panicGuide": "See next-metrics/lib/metrics/services.js and set metrics for the service, then release next-metrics and rebuild this app.",
"severity": 3,
"businessImpact": "We don't have any visibility with unregistered services.",
"technicalSummary": "Set up services' metrics in next-metrics/lib/metrics/services.js to send to Graphite."
},
```
The `next-url-mgmt-service` health checks have now been added to Heimdall …

Add https://url-management-api.in.ft.com/api to services

---

lib/metrics/services.js

This endpoint is called by next-es-interface and currently there is a healthcheck error fired because it is not measured by next-metrics.

Add next-live-event-notification-poc to the list of services

---

lib/metrics/services.js

Updates the coronavirus stats endpoint to match the new url https://ig.ft.com/coronavirus-chart/data-map-v2__world.json

Updates the coronavirus stats endpoint

---

lib/metrics/services.js

This is a new endpoint exposed by Membership to allow `next-messaging-guru` to display messages containing the remaining count of allowed articles on a user by user basis.
As this is missing, its currently causing the healthchecks to fail (https://heimdall.ftops.tech/system?returnTo=%2Foperations&code=next-messaging-guru#monitored-checks-list)

fix: add new access counted content endpoint

---

lib/metrics/services.js
test/unit/http.spec.old.js

We are seeing the alert on Heimdall for `Metrics: All services for retention registered in next-metrics (severity 3)`. Unfortunately it's difficult to the why it's failing unless it's failing at the point in time you're looking at it. 
At this point in time, it fails on `"checkOutput": "https://www.ft.com/__feedback-api/v1/survey services called but no metrics set up.",` - which makes sense because we added feedback functionality to `next-retention` in mid-August (https://github.com/Financial-Times/next-retention/pull/463).

NOPS-346 added next-feedback-api to services

---

README.md

This note no longer applies as the Node version upgrade and necessary amends were applied in this PR https://github.com/Financial-Times/next-metrics/pull/337.

Remove outdated README note

---

lib/metrics/services.js

[NOPS-354][NOPS-354]
Calls to Smartology API need to be registered in `next-metrics` to avail of the monitoring tools that alert us if the API starts returning error responses.
See also https://monitoring-manager.ftops.tech/validate-healthcheck?url=https://ads-api.ft.com/__health
[NOPS-354]: https://financialtimes.atlassian.net/browse/NOPS-354

NOPS-354 Register Smartology in next-metrics Services

---

lib/metrics/services.js

New domain added: voltdb-api-global.in.ft.com.  This is the Fastly service which provides regional failover of the voltdb apis.

New domain name for routing voltdb-api requests through Fastly

---

lib/metrics/services.js

No such Heroku app called `ft-next-myft-api-test` exists:
Visiting https://ft-next-myft-api-test.herokuapp.com results in **No such app**.
There are still a few bits of architecture for this app hanging around (as per below list), but my suspicion is that the Heroku app was removed but these other parts were left hanging.
- Hanging code references: https://github.com/search?q=user%3AFinancial-Times+ft-next-myft-api-test&type=Code
- Fastly service: https://manage.fastly.com/configure/services/62y0WLfLbWvsUnbcT3Aw92
- DNS entry: https://github.com/Financial-Times/dns/blob/master/config/main/ft.com.yaml#L5977-L5980

Remove ft-next-myft-api-test references

---

lib/metrics/services.js

Story: https://financialtimes.atlassian.net/browse/ACQ-517
Added `b2b-students-barrier-eligibility-checkpoint` matcher for URLs starting with `https://www.ft.com/__b2b-student-check`,

[ACQ-517] Add B2B students barrier service to metrics configuration

---

lib/metrics/services.js

Updates value to reflect change of name of active Preflight Heroku Canary app.

Update ft-next-preflight-canary URL

---

.circleci/config.yml
README.md

[Ticket CPP-442 Upgrade GitHub repos from `master` to `main`](https://financialtimes.atlassian.net/browse/CPP-442)<br/><br/>As an organisation we are moving away from the usage of `master` as a central branch and switching it to `main`, this is to avoid using unnecessary language that can be offensive. This PR is for making those changes. <br/><br/>This PR was created using a nori script<br/><br/>_Nori is a command-line application for managing changes across multiple (usually Github) repositories._

CPP-442 Upgrade GitHub repos from master to main

---

lib/metrics/services.js

This was missing. Not sure why this hasn't been picked up before. Is needed to display featured graphics on stream pages.

Add  ft-next-graphics-api-proto to services.js

---

lib/metrics/services.js

MyFT API cache health check is using the Fastly Realtime service and needs this metric to be added ([see MyFT API]( https://github.com/Financial-Times/next-myft-api/blob/59421e4d4ded829772074cb12f1dbc6368f08c98/server/libs/health-checks/cache-hit.js)) file related.
(collaboration with @taraojo @fenglish)
[Jira](https://financialtimes.atlassian.net/browse/CON-194)

Added Fastly Realtime to register it's metrics

---

lib/metrics/services.js

Fix regex to match recommended-reads-api calls http and https requests (all other CAPI regex in this file do the same).
[Jira](https://financialtimes.atlassian.net/browse/CON-747)

fix ontotext-popular service regex

---

lib/metrics/services.js

[Ticket CPP-474](https://financialtimes.atlassian.net/browse/CPP-474)
Ideally, we would want for `next-vault-sync` to only use v2 endpoints, but the CircleCI `/:project/settings` API endpoint has not been migrated by them to v2, so we need to keep using some v1 API endpoints in the mean time.

CPP-474 - next-vault-sync API call not registered in next-metrics

---

lib/metrics/services.js

Relates to this change in next-article: https://github.com/Financial-Times/next-article/pull/4205/files
Changes url `https://ig.ft.com/coronavirus-chart/data-map-v2__world.json` to `https://ft-ig-content-prod.s3-eu-west-1.amazonaws.com/v2/Financial-Times/data-journalism-covid-trajectories/main/world-map.json`

Update ig-coronavirus-map to new endpoint

---

lib/metrics/services.js

Adds the voucher service that is used and previously not registered:
`https://api.ft.com/print/v1/vouchers`

Add vouchers service

---

lib/metrics/services.js

These live blogs used to be powered by wordpress but we aim to decommission wordpress so we have moved the data into an S3 bucket.
I have added services for returning the posts data and also the images separately as it will help us monitor this change.

Add the old live blog assets services

---

lib/metrics/services.js

next-graphics-page has a [slightly different search url](https://github.com/Financial-Times/next-graphics-page/blob/master/server/checks/main.js#L15) so the 'all services registered' healthcheck goes off because it is not included in this list. 
This PR extends the regex to allow for both search urls.

NOPS-818: Allow embeds in ES search url

---

lib/metrics/services.js

Replace:
```js
/^https?:\/\/api\.ft\.com\/concepts\/[\w\-]+/
```
with:
```js
/^https?:\/\/api\.ft\.com\/concepts\/?[\w\-]{0,}/
```
as the former does not match `https://api.ft.com/concepts` with out anything additional on the path

fix: fix regex for capi-v2-concepts in services.js

---

lib/metrics/services.js

Add the new secured DeviceAtlas URL (`https://api.ft.com/spoor-device-atlas`) to the metrics
> We are migrating our DeviceAtlas service to another domain but we need to still support the old one so we updated the original regex to match both of them.
[DATA-4399](https://financialtimes.atlassian.net/browse/DATA-4399)

DATA-4399 Register the new secured device-atlas url to next-metrics services

---

lib/metrics/services.js

We are decommissioning the graphics hub so these services will no longer be required

Remove graphics page and graphics api

---

lib/metrics/services.js

This was removed as we weren't sure what was still using it, it turns out the stream page was using it still and so we are adding it back in

Add graphics-api-proto service

---

package.json

The hack added in #431 to stop installations failing when using an older version of npm has now been refined to be compatible with Volta and no longer a hack.

Put npm 7 check back into preinstall script

---

lib/metrics/services.js

these pertain to the old old `ammit-anubis` service, which has been decommissioned since 2019, not `next-anubis-config-api` and `next-anubis-scheduled-jobs` that replaced it, lol

CPP-661 remove ammit-anubis references

---

lib/graphite/client.js

A suggested change removing this noisy log. It is constantly loggin on opening and closing a socket but not sure if anyone benefits from it. Open for discussion! 👍🏻

Disable noisy log on every socket opening/closing

---

package-lock.json
package.json

next-metrics is listed as one of the providers for vulnerable `lodash` version to next-api.
However according to `package-lock.json`, next-metrics is using the latest(invulnerable) version already. 
I'm not sure the reason why snyk alerts this app. However I'm going to change the `package.json` and I would like to see whether snyk picks up the version correctly or not.
([link](
https://app.snyk.io/org/customer-products/project/52549f05-14d7-4b56-bba7-3ca83742fa57#issue-SNYK-JS-LODASH-590103))

Make sure lodash is invulnerable version

---

lib/metrics/services.js
package-lock.json

Fixes the following alert:
heimdall alert for the following [FT.com](http://ft.com/) Subscribe Page - Metrics: All services for subscribe registered in next-metrics - [https://test.salesforce.com/services/oauth2/token> services called but no metrics set up. can you help/advise <https://heimdall.ftops.tech/system?returnTo=%2Foperations&code=next-subscribe#monitored-checks-list>  and   <https://ft-next-subscribe-eu.herokuapp.com/__health](https://test.salesforce.com/services/oauth2/token%3E%20services%20called%20but%20no%20metrics%20set%20up.%20can%20you%20help/advise%20%3Chttps://heimdall.ftops.tech/system?returnTo=%2Foperations&code=next-subscribe#monitored-checks-list%3E%20%20and%20%20%20%3Chttps://ft-next-subscribe-eu.herokuapp.com/__health) …

ACQ-1448: add salesforce auth test url

---

lib/metrics/services.js

Fixed the alerts in https://heimdall.ftops.tech/system?code=next-preflight
Alerts are happening as we have recently updated the next-preflight to use a new API endpoint. https://github.com/Financial-Times/next-preflight/pull/615

Update endpoint for barrier-guru api

---

lib/metrics/services.js

This service should track everything in the .well-known directory of ft.com which includes https://www.ft.com/.well-known/security.txt (which we monitor programatically).

Add service for www-well-known

---

lib/metrics/services.js

This is alerting because next-health is now requesting this endpoint but we don't store metrics for it.
I don't know why this wasn't causing alerts when next-vault-sync was requesting it.

[FTDCS-169] Add www.ft.com/__verify-ft-next-backend-keys

---

.circleci/config.yml
README.md
lib/metrics.js
lib/metrics/fetch.js
test/unit/lib/metrics.spec.js
test/unit/lib/metrics/fetch.spec.js

Why ? 
Right now this library only instruments global.fetch variable that is usually created by isomorphicfetch . But in some apps it is been used node-fetch due to it has mor capabilities. 
So I create this PR in order this other apps could instrument node-fetch or other instance. This changes keeps retrocompatibility.
I Added two optional parameters in init method of metrics :
- "fetchInstance" in this parameter  we can pass an instance that we want to instrument. For example we can pass a node-fetch function 
- "overrideGlobalFetch"  this parameter is a boolean . By default is true. What it does is set global.fetch and instrument it.
Example:
```
const fetch = require('node-fetch')
const metrics = require('next-metrics')
const fetchInstrumented = metrics.init({fetchInstance : fetch }); …
```

Instrument other fetch instances not only global.fetch

---

lib/metrics/services.js

Why ?
Last week we have changed next-es-interface instrumenting almost all fetch that this app does. So on Friday there were an alerts notifying that a service wasn't registered in next-metrics from this app.
```
"checkOutput": "https://d1e00ek4ebabms.cloudfront.net/production/uploaded-files/ft-news-briefing-2e004171-2412-45a7-969b-31ddb3890ac8.png services called but no metrics set up."
```

add cloudfront.net services to next-metrics

---

lib/metrics/services.js

The original regex of `/^https:\/\/api.ft.com\/newsletters\//` only works if there is a `/` after `newsletters` but it looks like it's not always the case. This PR removed the last `/` which should work to catch the base url. It also adds a catch-all `.*` for all extensions of the URL. 
Ticket https://financialtimes.atlassian.net/browse/ACC-1799

ACC-1799 improve newsletters regex

---

lib/metrics/services.js

next-health is calling this API to gather application metrics.

Add Heroku Metrics to list of services

---

lib/metrics/services.js

Add service pointing to aws s3 that is fetched by next-article for editorial components feature

add service to fetch index editorial components in next-article

---

lib/metrics/services.js

Add the GraphQL gateway URLs (both test and prod) to the list of allowed services. 
This change is required to mitigate this alert:
It's firing because we've made changes to the `n-membership-sdk` so that it calls `https://api-t.ft.com/graphql/v1/api` and `https://api.ft.com/graphql/v1/api` instead of the direct GraphQL endpoints
[Ticket](https://financialtimes.atlassian.net/jira/software/c/projects/ACC/boards/1461?modal=detail&selectedIssue=ACC-1932)

ACC-1932 Add graphql-gateway urls to services allowed

---

lib/metrics/services.js

CPREL-341
https://financialtimes.atlassian.net/browse/CPREL-341
> We discovered this bucket while working on the incident response to `next-navigation-api`.
>
> It’s mentioned in the codebase but doesn’t appear used anywhere in production. The navigation is the same as it was in 2017.
> - [ ] Remove references to ft-next-navigation S3 bucket from anywhere you can find it

Remove references to unused next-navigation S3 buckets

---

lib/metrics/services.js

The new design from `next-newsletter-signup` uses the feed from `next-stream-page` to get some data.
Example urls:
https://www.ft.com/unhedged?format=json
https://www.ft.com/inside-politics?format=json
https://www.ft.com/swamp-notes?format=json

Adds newsletter feed regex

---

lib/metrics/services.js

It looks like salesforce is now pointing to a uat url.
next-subscribe needs to talk to salesforce to get some licence / contract information.
The salesforce URL is returned to next-subscribe dynamically here: https://github.com/Financial-Times/next-subscribe/blob/0b277c0e05b0c671f9e03659f62609bcbf5728dd/server/middleware/get-licence-contract.js#L72-L74
This causes next-subscribe to alert.
Ticket:
https://financialtimes.atlassian.net/browse/ACQ-2101

ACQ-2101: add salesforce uat url

---

.circleci/config.yml
package-lock.json
package.json

No dependency bumps because we're not releasing a new major of n-logger.

Drop Node.js 14 support

---

lib/metrics/services.js

Using the system code as the metric name: https://biz-ops.in.ft.com/System/snr-engagement-metrics-api
Also it's wierd that we're not getting the standard alert firing as this is missing in production.

Add snr-engagement-metrics-api service

---

lib/metrics/services.js

Alerting in preflight. Usage is here: https://github.com/Financial-Times/next-preflight/blob/main/server/tasks/zephr-access-decision.js

Add metrics URLs for Zephr

---

lib/metrics/services.js

The subs transition endpoint is now used in next-profile as part of a journey that allows users to change their payment term from Monthly to Annual
https://github.com/Financial-Times/next-profile/pull/1437/files#diff-83c67bc738ae4ae0e9bb9d98d44a80fe8e783947ec9c0b9a35d564aa01e17d95R66

Add the subs transitions endpoint as a service

---

lib/metrics/services.js

Jira ticket: [HIVE-1465](https://financialtimes.atlassian.net/browse/HIVE-1465)
Added regex for live events api url
[HIVE-1465]: https://financialtimes.atlassian.net/browse/HIVE-1465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add metrics URLs for live events api

---

lib/metrics/services.js

Adds the subs-graphql endpoints (test and prod) to the services
Usage in next-retention

adds urls for subs-graphql

---

lib/metrics/services.js

Apparently next-retention is throwing an alert for ops team because of unmonitored metrics that we have not added.
This PR adds the metrics that are missing for use to properly monitor all the end points that we are calling in next-retention.
[heimdall](https://heimdall.ftops.tech/system?code=next-retention#monitored-checks-list)
[Jjira ticket](https://financialtimes.atlassian.net/browse/ACC-2558)

chore: Add unmonitored urls for next-retention to  metrics

---

lib/metrics/services.js

Ticket - https://financialtimes.atlassian.net/browse/ACQ-2405
This is a PR to add url 'https://api.ft.com/subs/query/api/offers-by-country-code' which is being hit by next-barrier-page in services.js
The change is to fix Heimdall error mentioned in a message - https://financialtimes.slack.com/archives/CSVRXFV6F/p1695389145298989

Adding offers by country code api in services

---

lib/metrics/services.js

Earlier regex - `/^https:\/\/api\.ft\.com\/subs\/query\/api\/offers-by-country-code\/.*/`
This was not right as the URL is - `https://api.ft.com/subs/query/api/offers-by-country-code `
New regex - `/^https:\/\/api\.ft\.com\/subs\/query\/api\/offers-by-country-code/`

Fixing regex for offers-by-country-code-api

---

lib/metrics/services.js

Content discovery team needs to migrate `next-myft-api` from `VoltDB` domains to `SingleStoreDB` ones.
[Migration guide](https://docs.google.com/document/d/12TC2gyqdz0gb8MOQqXSrW0G7ttfo3jEnakwR9BOeTtU/edit) 
[JiraTask](https://financialtimes.atlassian.net/jira/software/c/projects/CON/boards/1061?assignee=712020%3Adda768db-49f7-48a4-8522-9de57cd1bdfb&selectedIssue=CON-2875)
Migration PR > https://github.com/Financial-Times/next-myft-api/pull/952
List of new domains:
- https://singlestore-api-global.in.ft.com/
- https://singlestore-api-eu.in.ft.com/
- https://singlestore-api-us.in.ft.com/
- https://singlestore-api-test.in.ft.com/
- https://singlestore-api-eu-test.in.ft.com/
- https://singlestore-api-us-test.in.ft.com/

[CON-2875] Add `singlestore-api` service to the registry

---

lib/metrics/services.js

**Description**
Added endpoint was considering most path params after similarity word, which is not correct.
Updated to reflect that.
All details in this [JIRA ticket](https://financialtimes.atlassian.net/browse/CON-3004).

[CON-3004] - Updated recommendations similarity endpoint

---

lib/metrics/services.js

Adding following 2 apis in the services list -
`https://api.ft.com/redeemable-email-tokens/*`
`https://api-t.ft.com/redeemable-email-tokens/*`
We have migrated redeemable token logic from `n-membership-sdk` to `next-subscribe`. This PR adds missing APIs to the APIs list.
https://heimdall.ftops.tech/system?returnTo=%2Foperations&code=next-subscribe#monitored-checks-list
https://financialtimes.atlassian.net/browse/ACQ-2655

Adding redeemable-email-tokens apis

---

README.md

It's 50/50 whether an engineer makes a minor or patch release of next-metrics when they add a service. Since v10 it's been exclusively patch releases which isn't really correct. Let's clarify the documentation a bit.

Clarify the release process

---

lib/metrics/services.js

Ticket: https://financialtimes.atlassian.net/browse/ACQ-2655
Heimdall alerts: Metrics: All services for subscribe registered in next-metrics
https://heimdall.ftops.tech/system?returnTo=%2Foperations&code=next-subscribe
URLs causing the alerts: https://api.ft.com/idm/v1/consent/users/*
Url is valid, checked in postman
```
curl --location 'https://api.ft.com/idm/v1/consent/users/***/FTPINK' \
--header 'x-api-key: ***' \
--header 'Cookie: FTAllocation=***; FTClientSessionId=***'
```
Documented in confluence:
- https://financialtimes.atlassian.net/wiki/spaces/AIM/pages/7879196773/API+Gateway+current+state
- https://financialtimes.atlassian.net/wiki/spaces/PAPI/pages/2697265319/API+Policies

next-subscribe alerts when it fetches consent

---

lib/metrics/services.js

This PR is a part of [decommission myFT desktop push notifications and n-service-worker](https://financialtimes.atlassian.net/browse/CON-3128)

Remove n-service-worker from services.js

---

lib/metrics/services.js

We're connecting to this domain from next-subscribe and next-barrier-page which is causing alerts.

Add sub(x) AWS domain

---

lib/metrics/services.js

Required for migration from Spark Lists API to Spark Pages API  see https://github.com/Financial-Times/dotcom-pages/pull/558.

Add Spark Pages API

---

lib/metrics/services.js

Sub(x) has changed their endpoint to - https://event.subxtech.com/www.ft.com/SendEventData

Incorporating new Sub(x) endpoint

---

lib/metrics/services.js

We are adding an API call to pro-central-banking in n-myft-navigation (https://github.com/Financial-Times/n-myft-subnavigation/pull/33), so I'd like to include the URL in the list of services to monitor the requests coming from consuming apps using n-express.
Please note that I probably don't have permissions in this repo to merge and release a new tag so I need someone from CP to do that after the PR is approved.
Thank you!

add pro-central-banking to the list of services

---

lib/metrics/services.js

Adding the api.ft.com/subs/query trialist check API endpoint and its test equivalent

fix: ci-2326 add subs graphql API to services

---

lib/metrics/services.js

Removing popular-api /articles service since it'll be removed [here](https://github.com/Financial-Times/next-popular-api/pull/174)

CON-3412 - remove popular-api /articles service since it has been removed

---

lib/metrics/services.js
package-lock.json

This isn't really needed and some services are calling it without the slash.

Remove trailing slash from ip-voltdb-api

---

README.md
lib/metrics/fetch.js
lib/metrics/services.js
test/unit/lib/metrics/fetch.spec.js

This adds in a default service name instead of marking all unrecognised services as uninstrumented. This is the first step towards allowing us to make broader metrics/n-express changes without blocking teams from doing their work.
To get a default value we replace `.` in the request URL's host name with `-`. If we can't parse out a hostname then we default to `unknown`.
**Note to reviewers:** we had to change some indentation so [ignoring whitespace changes will make this easier to review](https://github.com/Financial-Times/next-metrics/pull/583/files?w=1).
---
See-also: [CPREL-1123](https://financialtimes.atlassian.net/browse/CPREL-1123)
[CPREL-1123]: https://financialtimes.atlassian.net/browse/CPREL-1123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …

Default service names to reduce alerting
