lib/metrics/ft-api-client/v1.js
used correct event names for responses
avoided ever-growing lists!
=> added elastic search

lib/metrics/express/http-request.js, lib/metrics/express/http-response.js
=> prevent double reporting of req/res metrics

lib/metrics.js
=> Don't allow next-metrics to be initialised twice

lib/metrics/fetch.js
=> multiple instrumentation attempts of fetch shouldn't throw

lib/graphite/client.js
Prevents exceptions being thrown when graphite server is offline
=> Add error handlers to ftSocket

lib/metrics/fetch.js
=> Measure timeouts separate from other failures

lib/metrics.js
=> Add region to next-metrics

lib/metrics/express/http-response-v2.js
=> splitting express metrics by request method

lib/metrics.js
I accidentally broke http metric counts. I'm gonna add tests in another PR. @aintgoin2goa @matthew-andrews
=> Fixed bug with registering http reporters

lib/metrics/services.js
e.g. https://app.getsentry.com/nextftcom/ft-next-graphql-api/group/87739513/
=> Add Alphaville to services

lib/metrics/services.js
https://app.getsentry.com/nextftcom/ft-next-stream-page/group/89696008/
=> Fixed regex for https://next-es-interface.ft.com/

lib/metrics/services.js
See: https://app.getsentry.com/nextftcom/ft-next-ab/group/92089054/
=> Added https://sessionapi-glb.memb.ft.com/

circle.yml, lib/metrics.js, lib/metrics/express/http-response.js, lib/metrics/fetch.js, lib/metrics/index.js, lib/metrics/system/process.js, package.json
=> Bump to NBT v5 and fix linting errors

lib/metrics/services.js
https://app.getsentry.com/nextftcom/ft-next-redirector/group/88358718/ - aws-elastic-v3-item-search
https://app.getsentry.com/nextftcom/ft-next-session-service/group/96355585/ - dam
https://app.getsentry.com/nextftcom/ft-next-concepts-api/group/90856766/ - v3_api_v2/item/_mget
=> Add missing hostnames to service metrics

lib/metrics/services.js
=> Add hui to services

lib/metrics/services.js
https://app.getsentry.com/nextftcom/ft-next-popular-api/issues/105789566/
=> Add keen to metrics services

lib/metrics/services.js
/cc  @phamann Reduce the sentry noise
=> Add myft test API to service dependences

lib/metrics/services.js
=> Add Graphene DB to service metrics

lib/metrics/services.js
=> Add missing metrics endpoints

lib/metrics/services.js
/cc @aintgoin2goa 
causing https://app.getsentry.com/nextftcom/ft-next-opt-in-out/issues/113962387/
=> Add www.ft.com to the instrumented fetch code

lib/metrics/services.js
Fixes https://app.getsentry.com/nextftcom/ft-next-opt-in-out/issues/117100482/
=> Added s3 redshift to the fetch metrics

lib/metrics.js
1. The logic for choosing a platform was incorrect, causing the platform option to be ignored
2. When I removed the defaultAggregators I also removed the custom ones
=> fixing various issues with previous changes

lib/metrics/services.js
API written by Fahad Khan for the light sign-up prototype
=> Added anonymous email d-list API

lib/metrics/services.js
For stream page brand page design https://github.com/Financial-Times/next-stream-page/pull/936
=> add capi v2 brands api

lib/metrics/services.js
Sorts out https://app.getsentry.com/nextftcom/core-application/issues/122165405/
=> Registering the content classification api service

lib/graphite/client.js, lib/metrics.js, lib/metrics/express/http-response.js, lib/metrics/fetch.js, lib/metrics/system/process.js, tests/http.spec.js
because max and mean feels like a very blunt tool sometimes @commuterjoy @matthew-andrews 
Question: Should I just create a generic 'histogram flush' utility? There are subtle differences between each one currently, but prob not important
=> added median and 95th percentile metrics to all histograms

lib/metrics/services.js
/cc @adgad @leggsimon @andrewgeorgiou1981
=> add speedcurve api for ads monitoring

README.md, index.js, lib/metrics.js, lib/metrics/express/http-response.js, package.json, tests/http.spec.js
=> ability to allocate responses for a given response to a named bucket

lib/metrics/services.js
No more Heroku.
/cc @mclarke47
=> Update user subs status

lib/metrics/services.js
Will send the metrics correctly and fix the errors being sent to sentry
=> Adds the email platform to the services

lib/metrics.js
Shouldn't have deleted it in https://github.com/Financial-Times/next-metrics/pull/116
=> Needs fetch proxy

lib/metrics/services.js
For: https://github.com/Financial-Times/next-product-selector/pull/77
=> Added subs to metrics file for product-selector scraper

lib/metrics/services.js
Adds metrics tracking for services used by the B2B sign up flow.
=> B2B Service Routes

lib/metrics/services.js
to fix this sentry issue https://app.getsentry.com/nextftcom/ft-next-stream-page/issues/139799574/
=> ig-stream-content service

lib/metrics/services.js
=> Adding dfp and ads-api as services

lib/metrics/services.js
=> Add endpoints for acc-licence-svc via beta-api.ft.com

README.md, lib/graphite/client.js, lib/metrics.js, tests/client.spec.js
=> enable separate keys for internal and external graphite

lib/metrics/fetch.js
=> Add: 4xx + 5xx fetch response time

lib/metrics/services.js
https://github.com/Financial-Times/spoor-enrichment/pull/513
=> Segment ID API host name change

lib/metrics/services.js
@GlynnPhillips noticed these were missing from the spoor stats
=> Device Atlas host names

lib/metrics/services.js
cc: @TheoLeanse 
To stop it throwing errors in streams
https://sentry.io/nextftcom/ft-next-stream-page/
=> Add storylines service

lib/metrics/services.js
=> ft-next-video-editor metrics should use the CDN

lib/metrics/services.js
Fixes https://sentry.io/nextftcom/ft-next-dni-dashboard/issues/211069929/
@andygout
=> Add DNI service

lib/metrics/services.js
=> Add prod CAPI internalcontent endpoint

lib/metrics/fetch.js
mulling this over on the way home, this is a sticking plaster for the long regex list
=> more efficient look up of services

lib/metrics/services.js
- added missing service url check
=> [ADD] janetbot service url

lib/metrics/services.js
For preflight performance budgeting
=> add consent proxy service to metrics

lib/metrics/services.js
=> Add bitly service

lib/metrics/services.js
=> Add services for next-video-editor

lib/metrics/services.js
Adds next-retention to list of registered services
=> Add next retention app

lib/graphite/client.js, package.json
=> Remove use of debug

lib/graphite/client.js, lib/metrics/system/process.js, package.json
=> Upgrade lodash

lib/metrics/services.js
Don't know what it is, but next-signup calls it.
=> Add membership-idm

lib/metrics/services.js
This reverts commit 90e1b1dc661c8e3e0a27296639e809ad787352c2.
=> Delete the word wise API

lib/metrics/services.js
Supporting the new Graphite system.
Relates to https://github.com/Financial-Times/next/issues/170.
=> Update the internal graphite pattern

lib/metrics.js
Also added a bunch of comments
🐿 v2.10.3
=> Added _canary to the 'instance' in the metric prefix

lib/metrics.js
=> Bugfix: 'prefix' -> 'instance'

lib/metrics/services.js
https://github.com/Financial-Times/next/wiki/Beacon-and-Keen
=> Removes the reference to beacon

lib/metrics/services.js
=> Added ft-next-ammit-anubis-bayes endpoint to services.js

lib/metrics/services.js
While looking at another failing check for Ops Cops, I noticed another failing one saying this was missing.
=> Update services.js with myft-page info.

lib/metrics/services.js
add myft-proxy and topic-tracker-api to list of services
=> add myft-proxy and topic-tracker-api to list of services

lib/metrics/services.js
I've added the endpoints for both Comments API and Coral API.
=> Add APIs related to Comments to list of services

lib/metrics/services.js
Removes next-signup + next-signup-api
=> chore: remove decommed services

lib/metrics/services.js
request added in https://github.com/Financial-Times/next-ammit-api/pull/706
=> add ip-voltdb-api service

lib/metrics/services.js
Added coronavirus vaccination polling endpoint to services.js
=> added corona virus vaccination service

lib/metrics/services.js
- Update systemCode: `ft-next-video-editor` -> `ip-ovide`
- Update URLs references: `ft-next-video-editor` -> `ip-ovide`
=> Update ip ovide naming

lib/metrics/services.js
Adds api.ft.com/concepts to list of named services.
=> feat: add api.ft.com/concepts to list of named services

lib/metrics/services.js
Title says it all :)
https://financialtimes.atlassian.net/browse/NOPS-848
=> [NOPS-848] Add https://api-t.ft.com/newspaper/fulfilment/options to the metrics

lib/metrics/services.js
This is now being called as of a recent preflight change
https://github.com/Financial-Times/next-preflight/commit/39114456
=> Add sessionapi-test.memb.ft.com

lib/metrics/services.js
[next-discovery-pages](https://github.com/Financial-Times/next-discovery-pages) fetches data from this API
=> Add capi-v2-page api

lib/metrics/services.js
Add Membership newsletter service to list of registered services
=> Add Membership newsletter service to list of registered services

lib/metrics.js, test/unit/lib/metrics.spec.js
A small improvement that affects instance prefix calculation.
Signed-off-by: Erdoan Hadzhiyusein <erdoan.hadzhiyusein@ft.com>
=> Improve instanceKey overriding and the test for it

lib/metrics/services.js
@ludrob, as [requested](https://financialtimes.atlassian.net/browse/ACQ-953?focusedCommentId=520313)
=> ACQ-953: Added metrics scraping for membership-events svc

lib/metrics/services.js
Removing b2b students barrier related code. This barrier is no longer used.
https://financialtimes.atlassian.net/browse/ACQ-1350
=> ACQ-1350: cleaning up b2b students barrier code

lib/metrics/services.js, package-lock.json
adding a 'graphql-test': https:api-t.ft.com\graphql\ entry in next-metrics/lib/metrics/services.js
Ticket https://financialtimes.atlassian.net/browse/ACC-1874
=> ACC-1874 Add url to next-metrics

lib/metrics/services.js
Register new dotcom-pages API requests
=> register dotcom-pages api requests

lib/metrics/services.js
Register spark-lists.ft.com service
=> CON-2140 - register sparks-lists service

lib/metrics/services.js
**Description**
Added service entry for Spark Lists API
=> [CON-2349]: Add Spark Lists API services entry

lib/metrics/services.js
=> Update services.js to include Utopia Analytics

lib/metrics/services.js
add epaper NPD api services.
We add api-t.ft.com for testing but will be removed after test the flow
=> add NPD production and api services for epaper

lib/metrics/services.js
**Description**
Adds the recommended article endpoint.
=> [CON-2966] - Added Insights Recommended Articles endpoint

lib/metrics/services.js
=> add com-ft-next-media-renditions domain to registry

lib/metrics/services.js
Adding `relatedcontent` service (will be used by the Clips in the home-page
=> CON-3237 add relatedcontent service

lib/metrics/services.js
next-vault-sync is now decommissioned.
=> CPP-1657: remove next-vault-sync reference

lib/metrics/services.js
The route added in #554 was incorrect 🤦 !!
=> Fix spark pages API route

README.md
See-also: [CPREL-1127](https://financialtimes.atlassian.net/browse/CPREL-1127)
[CPREL-1127]: https://financialtimes.atlassian.net/browse/CPREL-1127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add a deprecation notice and timeline
